apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: smartlogistics-local
data:
  init-databases.sql: |
    CREATE DATABASE keycloak;
    CREATE DATABASE "ShipmentDB";
    CREATE DATABASE "TariffDB";
    CREATE DATABASE "BillingDB";
