apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: smartlogistics-local
data:
  appsettings.Kubernetes.json: |
    {
      "Keycloak": {
        "Authority": "http://keycloak:8080/realms/SmartLogistics"
      },
      "ReverseProxy": {
        "Clusters": {
          "shipment-cluster": {
            "Destinations": {
              "destination1": { "Address": "http://shipment-api/" }
            }
          },
          "tariff-cluster": {
            "Destinations": {
              "destination1": { "Address": "http://tariff-api/" }
            }
          },
          "billing-cluster": {
            "Destinations": {
              "destination1": { "Address": "http://billing-api/" }
            }
          },
          "notification-cluster": {
            "Destinations": {
              "destination1": { "Address": "http://notification-api/" }
            }
          }
        }
      }
    }
