FROM node:22-alpine AS build
WORKDIR /app
COPY web/smartlogistics-web/package.json web/smartlogistics-web/package-lock.json web/smartlogistics-web/.npmrc ./
RUN npm ci
COPY web/smartlogistics-web/ ./
RUN npm run build

FROM nginx:1.27-alpine AS final
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist/smartlogistics-web/browser /usr/share/nginx/html
EXPOSE 80
