server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /federation.manifest.json {
        add_header Cache-Control "no-cache";
    }

    location /i18n/ {
        add_header Cache-Control "no-cache";
    }
}
